/**
 * SEO content for /time/crontab-guru. Every statement was checked against the code;
 * re-verify these sources when upstream changes the tool:
 * - src/pages/tools/time/crontab-guru/service.ts lines 29-42
 * - src/pages/tools/time/crontab-guru/service.ts lines 25-27
 * - node_modules/cron-validator/lib/index.js lines 29, 78-79, 119-125, 152-153, 161; node_modules/cron-validator/package.json
 * - node run against node_modules/cron-validator (1.4.0) and node_modules/cronstrue/i18n (3.3.0) with the tool's options
 * - src/pages/tools/time/crontab-guru/service.ts lines 4-23
 * - src/components/Navbar/index.tsx lines 32-44 and 59-63; src/i18n/index.ts lines 31-43
 * - src/components/ToolContent.tsx lines 26-33; src/pages/tools/time/crontab-guru/index.tsx lines 51-53
 * - node_modules/cronstrue/i18n.js; node_modules/cronstrue/dist/cronstrue-i18n.js (grep count 0); node_modules/cron-validator/lib/index.js (grep count 0)
 * - src/pages/tools/time/crontab-guru/index.tsx lines 56-72; src/components/result/ToolTextResult.tsx lines 14, 26-50, 85
 * - src/pages/tools/time/crontab-guru/service.ts lines 21-42
 */
import type { ToolSeoOverride } from '../../types';

const content: ToolSeoOverride = {
  title: 'Cron Expression Explainer and Validator | Orvulix',
  description:
    'Paste a 5-field cron expression to see its schedule described in plain language. Checks the syntax and explains several expressions at once, one per line.',
  howTo: [
    'Type or paste a cron expression into the input box, for example 35 16 * * 0-5.',
    'To check several schedules at once, put each expression on its own line.',
    'Read the description on the matching line of the result. Invalid lines show Invalid crontab expression followed by the text you entered.',
    'To get descriptions in another language, change the site language in the navigation bar. If the result does not change after switching, edit the input to refresh it.',
    'Click Copy to clipboard, or click Download to save the descriptions as a .txt file.'
  ],
  examples: [
    {
      title: 'Weekday afternoon job',
      description:
        '35 16 * * 0-5 is explained as "At 04:35 PM, Sunday through Friday".'
    },
    {
      title: 'Every 5 minutes',
      description: '*/5 * * * * is explained as "Every 5 minutes".'
    },
    {
      title: 'Weekday names are rejected',
      description:
        '0 0 * * MON returns Invalid crontab expression: "0 0 * * MON". Use 0 0 * * 1 instead.'
    }
  ],
  notes: [
    'Expressions must have exactly 5 fields: minute, hour, day of month, month and day of week. Expressions with a 6th field for seconds are reported as invalid.',
    'Fields can use *, numbers, ranges (1-5), lists (1,15) and steps (*/5), and ? is accepted in the day-of-month or day-of-week field. Day of week runs from 0 to 6, with 0 for Sunday. 7, names such as MON or JAN, and macros such as @daily are rejected.',
    'Descriptions are generated by the cronstrue library in the site language for English, French, Spanish, German, Japanese, Chinese, Portuguese, Dutch and Russian. Other site languages get English.',
    'The tool validates and describes schedules but does not list upcoming run times.',
    'Validation and descriptions run in your browser with the cron-validator and cronstrue libraries, which make no network requests.'
  ],
  faq: [
    {
      question: 'Does it support seconds or 6-field cron expressions?',
      answer:
        'No. Validation runs with seconds disabled, so only the standard 5-field format (minute, hour, day of month, month, day of week) is accepted.'
    },
    {
      question: 'Why is 0 0 * * MON marked invalid?',
      answer:
        'Weekday and month names are not accepted. Use numbers instead, for example 0 0 * * 1 for Mondays at midnight. The day of week must be between 0 and 6.'
    },
    {
      question: 'Can I see the description in another language?',
      answer:
        'Yes. Change the site language. Descriptions are available in English, French, Spanish, German, Japanese, Chinese, Portuguese, Dutch and Russian. Hindi and Ukrainian fall back to English.'
    },
    {
      question: 'Does it show when the job will run next?',
      answer:
        'No. It shows whether each expression is valid and describes the schedule in words. It does not calculate run dates.'
    }
  ]
};

export default content;
